"""empty message

Revision ID: 3ebdfd86934
Revises: None
Create Date: 2014-05-08 19:33:48.016110

"""

# revision identifiers, used by Alembic.
revision = '3ebdfd86934'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
